- name: Update Website in Homelab

on:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Downloading tailscale, ssh
        run: |
          sudo apt update
          sudo apt install -y tailscale openssh-server

      - name: Starting up tailscale and connecting it to my Tailscale network
        run: sudo tailscale up --auth-key ${{ secrets.TSKEY_AUTH }}

      - name: Connecting to the homelab by ssh authentication
        run: |
          mkdir -p ~/.ssh/
          printf "%s\n" "${{ secrets.PKEY_FOR_RASPBERRYPI }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -p 6769 -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no hysc@100.95.1.73 "touch ~/testing-github-action"
