name: Update Website in Homelab

on:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      TS_USER: hysc
      TS_IP: 100.95.1.73

    steps:
      - name: Downloading tailscale, ssh
        run: |
          sudo apt update
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo apt install -y openssh-server

      - name: Creating ssh connecting to homelab alias
        run: alias ssh-hl='ssh -p 6769 -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $TS_USER@$TS_IP' 

      - name: Starting up tailscale and connecting it to my Tailscale network
        run: sudo tailscale up --auth-key ${{ secrets.TSKEY_AUTH }}

      - name: Connecting to the homelab by ssh authentication and Pulling from github
        run: |
          mkdir -p ~/.ssh/
          printf "%s\n" "${{ secrets.PKEY_FOR_RASPBERRYPI }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-hl "cd ~/UnixProject && git pull origin main"
      
      - name: Check html(CI)
        run: ssh-hl "cd ~/UnixProject && htmlhint "website.html""

      - name: Deploy Website(CD)
        run: |
          ssh-hl "
          sudo docker stop shwebsite || true &&
          sudo docker rm shwebsite || true &&
          cd ~/UnixProject &&
          sudo docker build -t unixprojectimagefinal:latest . &&
          sudo docker run -d -p 8080:67 --name shwebsite unixprojectimagefinal:latest"
          
          

      
      
      
      #- name: Copy html into index.html
       # run: ssh -p 6769 -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no hysc@100.95.1.73 "sudo docker cp /home/hysc/UnixProject/website.html 68ab2b4b6267:/usr/local/apache2/htdocs/index.html"

        

          
