name: Update Website in Homelab

on:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Downloading tailscale, ssh
        run: |
          sudo apt update
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo apt install -y openssh-server

      - name: Starting up tailscale and connecting it to my Tailscale network
        run: sudo tailscale up --auth-key ${{ secrets.TSKEY_AUTH }}

      - name: Connecting to the homelab by ssh authentication and Pulling from github
        run: |
          mkdir -p ~/.ssh/
          printf "%s\n" "${{ secrets.PKEY_FOR_RASPBERRYPI }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -p 6769 -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no hysc@100.95.1.73 "cd ~/UnixProject && git pull"
      
      - name: Check html
        run: ssh -p 6769 -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no hysc@100.95.1.73 "cd ~/UnixProject && htmlhint "website.html""

      - name: Copy html into index.html
        run: ssh -p 6769 -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no hysc@100.95.1.73 "sudo docker cp /home/hysc/UnixProject/website.html 68ab2b4b6267:/usr/local/apache2/htdocs/index.html"

        

          
